// ---------- printable test report: report.html?id=<formulation id> ----------
//
// The document the lab sends back to Hi-Tech Company. Hi-Tech Company can
// open it once the lab has released the results; the lab can open it at
// any time to preview, and until release it is marked DRAFT.

import { api } from "./api.js";
import { esc, fmtDate, specText, valueSummary, TEST_META, OUTCOME_TEXT, daysBetween } from "./format.js";

var sheet = document.getElementById("report");
var printBtn = document.getElementById("btn-print");
printBtn.onclick = function () { window.print(); };

function verdict(result) {
  var label = { pass: "Pass", fail: "Fail", recorded: "Recorded" }[result] || "Pending";
  return '<span class="verdict ' + esc(result || "pending") + '">' + label + "</span>";
}

function kv(label, value, cls) {
  return '<div class="kv"><span class="k">' + label + '</span><span class="v ' + (cls || "") + '">' + value + "</span></div>";
}

function showError(msg) {
  sheet.innerHTML = '<p class="error">' + esc(msg) + ' <a href="./">Go to the tracker</a></p>';
}

function renderReport(data) {
  var f = data.formulation;
  var released = f.status === "released";
  document.title = (f.reportNo ? f.reportNo + " · " : "") + f.name + " — Test report";

  var rows = (f.requestedTests || []).map(function (type) {
    var r = data.results.find(function (x) { return x.testType === type; });
    // Class + data-label let phones show each test as a labelled block.
    return '<tr><td class="r-test"><b>' + TEST_META[type].label + "</b>" + (r && r.notes ? '<div class="note">' + esc(r.notes) + "</div>" : "") + "</td>" +
      '<td class="r-specimen mono" data-label="Specimen / lot">' + esc((r && r.specimenId) || "—") + "</td>" +
      '<td class="r-measured" data-label="Measured">' + (r ? esc(valueSummary(r)) : "Not recorded") + "</td>" +
      '<td class="r-spec" data-label="Specification">' + esc(specText(f.specs, type)) + "</td>" +
      '<td class="r-verdict">' + verdict(r && r.result) + "</td>" +
      '<td class="r-tested" data-label="Tested">' + (r ? esc(fmtDate(r.testedAt)) + '<div class="note">' + esc(r.testedByName || "") + "</div>" : "—") + "</td></tr>";
  }).join("");

  var days = daysBetween(f.submittedAt, f.releasedAt);
  var html = '<header class="rh"><div><div class="org">Manna Rubber Park</div><div class="org-sub">Laboratory · Test report</div></div>' +
    '<div class="rh-meta">' +
    kv("Report no.", esc(f.reportNo || "Assigned on release"), "mono") +
    kv("Revision", f.revision ? String(f.revision) : "—") +
    kv("Issued", released ? esc(fmtDate(f.releasedAt)) : "Not issued") +
    "</div></header>";

  if (!released) html += '<div class="draft">Draft — not yet released to Hi‑Tech Company</div>';

  html += '<section class="grid">' +
    kv("Client", "Hi‑Tech Company") +
    kv("Sent in by", esc(f.submittedByName || "Unknown") + ", " + esc(fmtDate(f.submittedAt))) +
    kv("Formulation", esc(f.name)) +
    kv("Formulation / batch code", esc(f.code), "mono") +
    kv("Priority", f.priority === "urgent" ? "Urgent" : "Normal") +
    kv("Turnaround", days != null ? days + (days === 1 ? " day" : " days") : "—") +
    "</section>";

  if (f.description) html += "<section><h3>Composition / description</h3><p>" + esc(f.description) + "</p></section>";

  html += '<section><h3>Results</h3><div class="table-scroll"><table><thead><tr><th>Test</th><th>Specimen / lot</th><th>Measured</th><th>Specification</th><th>Verdict</th><th>Tested</th></tr></thead><tbody>' + rows + "</tbody></table></div></section>";

  html += '<section class="outcome"><h3>Overall outcome</h3><div class="outcome-row">' + verdict(f.outcome) +
    "<p>" + esc(f.outcome ? OUTCOME_TEXT[f.outcome] : "Not every requested test has been recorded yet.") + "</p></div></section>";

  if (f.labRemarks) html += '<section><h3>Lab remarks</h3><p class="remarks">' + esc(f.labRemarks) + "</p></section>";

  html += '<section class="sign grid">' +
    kv("Released by", released ? esc(f.releasedByName || "Unknown") + '<div class="note">Manna Rubber Park Laboratory</div>' : "—") +
    kv("Release date", released ? esc(fmtDate(f.releasedAt)) : "—") +
    "</section>";

  html += '<p class="fine">Results relate only to the samples tested. Pass/fail is judged against the acceptance limits Hi‑Tech Company supplied with the formulation; a test without limits is recorded only. Generated by the Formulation Test Tracker.</p>';

  sheet.innerHTML = html;
  printBtn.disabled = false;
}

var id = new URLSearchParams(location.search).get("id");
if (!id) {
  showError("No report was selected.");
} else {
  api("/reports/" + encodeURIComponent(id)).then(renderReport).catch(function (err) {
    if (err.status === 401) { location.replace("login.html?next=" + encodeURIComponent("report.html?id=" + id)); return; }
    showError(err.message || "Could not load the report.");
  });
}
